export const routes = {
  news: {
    list: '/news',
    detail: (slug: string) => `/news/${slug}`,
    create: '/news',
    update: (id: string) => `/news/${id}`,
    delete: (id: string) => `/news/${id}`,
    categories: '/news/categories',
    tags: '/news/tags',
    popularTags: 'news/tags/popular',
    analytics: (id: string) => `/news/internal/${id}/analytics`,
    comments: (slug: string) => `/news/${slug}/create-comment`,
    related: (slug: string) => `/news/${slug}/related`,
  },
  users: {
    list: '/users',
    detail: (id: string) => `/users/${id}`,
    update: (id: string) => `/users/${id}`,
    fetchAll: '/users/all',
  },
  analytics: {
    summary: '/analytics/summary',
    popular: '/analytics/popular',
  },
  siteConfig: {
    get: '/site-config',
    initialize: '/site-config/initialize',
    navigation: '/site-config/navigation',
    healthCheck: '/site-config/health-check',
    simpleHealthCheck: '/site-config/simple-health-check',
  },
  ads: {
    list: '/ads',
    create: '/ads',
    update: (id: string) => `/ads/${id}`,
    delete: (id: string) => `/ads/${id}`,
    details: (id: string) => `/ads/${id}`,
  },
  polls: {
    list: '/polls',
    create: '/polls',
    update: (id: string) => `/polls/${id}`,
    delete: (id: string) => `/polls/${id}`,
    vote: (id: string) => `/polls/${id}/vote`,
    removeVote: (id: string) => `/polls/${id}/vote`,
    winner: (id: string) => `/polls/${id}/winner`,
    admin: '/polls/all',
  },
}
